/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddPost: typeof import('./src/components/AddPost.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    DataView: typeof import('primevue/dataview')['default']
    DataViewLayoutOptions: typeof import('primevue/dataviewlayoutoptions')['default']
    Divider: typeof import('primevue/divider')['default']
    Dock: typeof import('primevue/dock')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Galleria: typeof import('primevue/galleria')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Image: typeof import('primevue/image')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    InlineMessage: typeof import('primevue/inlinemessage')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Page1: typeof import('./src/components/Page1.vue')['default']
    Page2: typeof import('./src/components/Page2.vue')['default']
    Password: typeof import('primevue/password')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabMenu: typeof import('primevue/tabmenu')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
    TestEmail: typeof import('./src/components/TestEmail.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    TriStateCheckbox: typeof import('primevue/tristatecheckbox')['default']
    VerificaitonPage: typeof import('./src/components/VerificaitonPage.vue')['default']
    VerificationPage: typeof import('./src/components/VerificationPage.vue')['default']
    VerifyEmail: typeof import('./src/components/VerifyEmail.vue')['default']
  }
}
